# Generated by Django 5.1 on 2024-08-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_user_enrollmentno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrollmentNo',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
